---
- name: include package list
  include_vars: vars/yay.yml

- name: install yay
  aur:
    name: yay

- name: manage packages
  aur:
    use: yay
    name: "{{ item.0 }}"
    state: "{{ item.value.state | default('latest') }}"
  loop: "{{ yay|dictsort }}"
