---
- name: Include package list
  include_vars: vars/yay.yml
  tags:
    - yay

- name: install key from keybase keyserver
  gpg_key:
    fpr: EB4F9E5A60D32232BB52150C12C87A28FEAC6B20
    keyserver: https://keybase.io/maximbaz/pgp_keys.asc

- block:
    - name: Install yay
      aur:
        name: yay

    - name: Manage packages
      aur:
        use: yay
        name: "{{ item.0 }}"
        state: "{{ item.value.state | default('latest') }}"
      loop: "{{ yay|dictsort }}"

  when: ansible_os_family == "Archlinux"
  tags:
    - yay
