---
- name: Include package list
  include_vars: vars/yay.yml
  tags:
    - yay

- name: Install yay
  aur:
    name: yay
  tags:
    - yay

- name: Manage packages
  aur:
    use: yay
    name: "{{ item.0 }}"
    state: "{{ item.value.state | default('latest') }}"
  loop: "{{ yay|dictsort }}"
  tags:
    - yay
