---
- name: Include pacman package list
  include_vars: vars/pacman.yml
  tags:
    - pacman

- name: Install yay
  aur:
    name: yay

- name: Manage pacman packages
  aur:
    use: yay
    name: "{{ item.0 }}"
    state: "{{ item.value.state | default('latest') }}"
  loop: "{{ pacman|dictsort }}"

  when: ansible_os_family == "Archlinux"
  tags:
    - pacman
