---
# Fonts: http://input.fontbureau.com/download/?customize&fontSelection=fourStyleFamily&regular=InputMonoNarrow-Regular&italic=InputMonoNarrow-Italic&bold=InputMonoNarrow-Bold&boldItalic=InputMonoNarrow-BoldItalic&a=0&g=0&i=serifs_round&l=serifs_round&zero=slash&asterisk=height&braces=0&preset=default&line-height=1.1&email=
- name: Creates system directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/usr/share/fonts/{{ ansible_user_id }}"
    - /etc/systemd/journald.conf.d
    - /etc/systemd/logind.conf.d
    - /etc/pacman.d/hooks

- name: copy system level configuration
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    remote_src: yes
  loop:
    - { src: 'files/etc/pulse/default.pa', dest: '/etc/pulse/default.pa' }
    - { src: 'files/etc/bluetooth/main.conf', dest: '/etc/bluetooth/main.conf' }
    - { src: 'files/etc/systemd/system/reflector.service', dest: '/etc/systemd/system/reflector.service' }
    - { src: 'files/etc/systemd/system/reflector.timer', dest: '/etc/systemd/system/reflector.timer' }
    - { src: 'files/etc/pacman.d/hooks/mirrorlist.hook', dest: '/etc/pacman.d/hooks/mirrorlist.hook' }
    - { src: 'files/etc/pacman.conf', dest: '/etc/pacman.conf' }
    - { src: 'files/etc/modprobe.d/v4l2loopback.conf', dest: '/etc/modprobe.d/v4l2loopback.conf' }
    - { src: 'files/etc/modules-load.d/v4l2loopback.conf', dest: '/etc/modules-load.d/v4l2loopback.conf' }
    - { src: 'files/etc/pam.d/polkit-1', dest: '/etc/pam.d/polkit-1' }
    - { src: 'files/etc/pam.d/sudo', dest: '/etc/pam.d/sudo' }
    - { src: 'files/usr/lib/udev/rules.d/60-net.rules', dest: '/usr/lib/udev/rules.d/60-net.rules' }
    - { src: 'files/usr/share/applications/Zoom.desktop', dest: '/usr/share/applications/Zoom.desktop' }
    - { src: 'files/etc/fuse.conf', dest: '/etc/fuse.conf' }
    - { src: 'files/usr/share/fonts/{{ ansible_user_id }}/InputMonoNarrow-Bold.ttf', dest: '/usr/share/fonts/{{ ansible_user_id }}/InputMonoNarrow-Bold.ttf' }
    - { src: 'files/usr/share/fonts/{{ ansible_user_id }}/InputMonoNarrow-BoldItalic.ttf', dest: '/usr/share/fonts/{{ ansible_user_id }}/InputMonoNarrow-BoldItalic.ttf' }
    - { src: 'files/usr/share/fonts/{{ ansible_user_id }}/InputMonoNarrow-Italic.ttf', dest: '/usr/share/fonts/{{ ansible_user_id }}/InputMonoNarrow-Italic.ttf' }
    - { src: 'files/usr/share/fonts/{{ ansible_user_id }}/InputMonoNarrow-Regular.ttf', dest: '/usr/share/fonts/{{ ansible_user_id }}/InputMonoNarrow-Regular.ttf' }
    - { src: 'files/etc/fonts/conf.d/30-font-aliases.conf', dest: '/etc/fonts/conf.d/30-font-aliases.conf' }
    - { src: 'files/etc/fonts/conf.d/75-joypixels.conf', dest: '/etc/fonts/conf.d/75-joypixels.conf' }
    - { src: 'files/etc/pipewire/media-session.d/media-session.conf', dest: '/etc/pipewire/media-session.d/media-session.conf' }
    - { src: 'files/etc/systemd/journald.conf.d/override.conf', dest: '/etc/systemd/journald.conf.d/override.conf' }
    - { src: 'files/etc/systemd/logind.conf.d/override.conf', dest: '/etc/systemd/logind.conf.d/override.conf' }
  tags:
    - pulseaudio
    - bluetooth
    - reflector
    - network
    - pacman

- name: Enable system services
  systemd:
    name: "{{ item }}"
    enabled: yes
  loop:
    - "NetworkManager.service"
    - "bluetooth.service"
    - "docker.socket"
    - "tlp.service"
    - "reflector.timer"
    - "pcscd.service"
  tags:
    - network
    - bluetooth
    - docker
    - tlp
    - reflector

- name: ensure group "docker" exists
  group:
    name: docker
    state: present
  tags:
    - docker

- name: add {{ ansible_user_id }} to "docker" group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  tags:
    - docker
