---
- name: Enable network services
  systemd:
    name: "{{ item }}"
    enabled: yes
  loop:
    - "iwd.service"
    - "systemd-networkd.socket"
    - "systemd-resolved.service"
    - "bluetooth.service"
    - "docker.socket"
  tags:
    - network
    - iwd
    - bluetooth
    - docker

- name: Enable iwd built-in network configuration
  blockinfile:
    path: /etc/iwd/main.conf
    create: yes
    block: |
      [General]
      EnableNetworkConfiguration=true
      RoutePriorityOffset=300
  tags:
    - network
    - iwd

- name: Colored pacman packages output
  lineinfile:
    dest: /etc/pacman.conf
    state: present
    regexp: "^(.*)Color"
    line: "Color"
  tags:
    - pacman

- name: ensure group "docker" exists
  group:
    name: docker
    state: present
  tags:
    - docker

- name: add {{ ansible_user_id }} to "docker" group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  tags:
    - docker

- name: copy system level configuration
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: 'files/pulse/default.pa', dest: '/etc/pulse/default.pa' }
    - { src: 'files/bluetooth/main.conf', dest: '/etc/bluetooth/main.conf' }
  tags:
    - pulseaudio
    - bluetooth
