---
- name: copy system level configuration
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    remote_src: yes
  loop:
    - { src: 'files/etc/pulse/default.pa', dest: '/etc/pulse/default.pa' }
    - { src: 'files/etc/bluetooth/main.conf', dest: '/etc/bluetooth/main.conf' }
    - { src: 'files/etc/systemd/system/reflector.service', dest: '/etc/systemd/system/reflector.service' }
    - { src: 'files/etc/systemd/system/reflector.timer', dest: '/etc/systemd/system/reflector.timer' }
    - { src: 'files/etc/pacman.conf', dest: '/etc/pacman.conf' }
    - { src: 'files/etc/modprobe.d/v4l2loopback.conf', dest: '/etc/modprobe.d/v4l2loopback.conf' }
    - { src: 'files/etc/modules-load.d/v4l2loopback.conf', dest: '/etc/modules-load.d/v4l2loopback.conf' }
  tags:
    - pulseaudio
    - bluetooth
    - reflector
    - network
    - iwd
    - pacman

- name: Enable system services
  systemd:
    name: "{{ item }}"
    enabled: yes
  loop:
    - "NetworkManager.service"
    - "bluetooth.service"
    - "docker.socket"
    - "tlp.service"
    - "reflector.timer"
  tags:
    - network
    - iwd
    - bluetooth
    - docker
    - tlp
    - reflector

- name: ensure group "docker" exists
  group:
    name: docker
    state: present
  tags:
    - docker

- name: add {{ ansible_user_id }} to "docker" group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  tags:
    - docker
