---
- name: copy system level configuration
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    remote_src: yes
  loop:
    - { src: 'files/etc/pulse/default.pa', dest: '/etc/pulse/default.pa' }
    - { src: 'files/etc/bluetooth/main.conf', dest: '/etc/bluetooth/main.conf' }
    - { src: 'files/etc/systemd/system/reflector.service', dest: '/etc/systemd/system/reflector.service' }
    - { src: 'files/etc/systemd/system/reflector.timer', dest: '/etc/systemd/system/reflector.timer' }
    - { src: 'files/etc/pacman.conf', dest: '/etc/pacman.conf' }
    - { src: 'files/etc/modprobe.d/v4l2loopback.conf', dest: '/etc/modprobe.d/v4l2loopback.conf' }
    - { src: 'files/etc/modules-load.d/v4l2loopback.conf', dest: '/etc/modules-load.d/v4l2loopback.conf' }
    - { src: 'files/etc/pam.d/polkit-1', dest: '/etc/pam.d/polkit-1' }
    - { src: 'files/etc/pam.d/sudo', dest: '/etc/pam.d/sudo' }
    - { src: 'files/usr/lib/udev/rules.d/60-net.rules', dest: '/usr/lib/udev/rules.d/60-net.rules' }
    - { src: 'files/usr/share/applications/Zoom.desktop', dest: '/usr/share/applications/Zoom.desktop' }
    - { src: 'files/etc/fuse.conf', dest: '/etc/fuse.conf' }
    - { src: 'files/etc/systemd/system/pacman-db-sync.service', dest: '/etc/systemd/system/pacman-db-sync.service' }
    - { src: 'files/etc/systemd/system/pacman-db-sync.timer', dest: '/etc/systemd/system/pacman-db-sync.timer' }
  tags:
    - pulseaudio
    - bluetooth
    - reflector
    - network
    - pacman

- name: Enable system services
  systemd:
    name: "{{ item }}"
    enabled: yes
  loop:
    - "NetworkManager.service"
    - "bluetooth.service"
    - "docker.socket"
    - "tlp.service"
    - "reflector.timer"
    - "pcscd.service"
    - "pacman-db-sync.timer"
  tags:
    - network
    - bluetooth
    - docker
    - tlp
    - reflector

- name: ensure group "docker" exists
  group:
    name: docker
    state: present
  tags:
    - docker

- name: add {{ ansible_user_id }} to "docker" group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  tags:
    - docker
