---
# Fonts: http://input.fontbureau.com/download/?customize&fontSelection=fourStyleFamily&regular=InputMonoNarrow-Regular&italic=InputMonoNarrow-Italic&bold=InputMonoNarrow-Bold&boldItalic=InputMonoNarrow-BoldItalic&a=0&g=0&i=serifs_round&l=serifs_round&zero=slash&asterisk=height&braces=0&preset=default&line-height=1.1&email=
- name: creates system directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/usr/share/fonts/{{ ansible_user_id }}"
    - /etc/systemd/journald.conf.d
    - /etc/systemd/logind.conf.d
    - /etc/pacman.d/hooks

- name: copy system level configuration
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    remote_src: yes
  loop:
    - { src: 'files/etc/bluetooth/main.conf', dest: '/etc/bluetooth/main.conf' }
    - { src: 'files/etc/systemd/system/reflector.service', dest: '/etc/systemd/system/reflector.service' }
    - { src: 'files/etc/systemd/system/reflector.timer', dest: '/etc/systemd/system/reflector.timer' }
    - { src: 'files/etc/pacman.d/hooks/mirrorlist.hook', dest: '/etc/pacman.d/hooks/mirrorlist.hook' }
    - { src: 'files/etc/pacman.conf', dest: '/etc/pacman.conf' }
    - { src: 'files/etc/modprobe.d/v4l2loopback.conf', dest: '/etc/modprobe.d/v4l2loopback.conf' }
    - { src: 'files/etc/modules-load.d/v4l2loopback.conf', dest: '/etc/modules-load.d/v4l2loopback.conf' }
    - { src: 'files/etc/sudoers.d/override', dest: '/etc/sudoers.d/override' }
    - { src: 'files/usr/lib/udev/rules.d/60-net.rules', dest: '/usr/lib/udev/rules.d/60-net.rules' }
    - { src: 'files/etc/fuse.conf', dest: '/etc/fuse.conf' }
    - { src: 'files/usr/share/fonts/{{ ansible_user_id }}/InputMonoNarrow-Bold.ttf', dest: '/usr/share/fonts/{{ ansible_user_id }}/InputMonoNarrow-Bold.ttf' }
    - { src: 'files/usr/share/fonts/{{ ansible_user_id }}/InputMonoNarrow-BoldItalic.ttf', dest: '/usr/share/fonts/{{ ansible_user_id }}/InputMonoNarrow-BoldItalic.ttf' }
    - { src: 'files/usr/share/fonts/{{ ansible_user_id }}/InputMonoNarrow-Italic.ttf', dest: '/usr/share/fonts/{{ ansible_user_id }}/InputMonoNarrow-Italic.ttf' }
    - { src: 'files/usr/share/fonts/{{ ansible_user_id }}/InputMonoNarrow-Regular.ttf', dest: '/usr/share/fonts/{{ ansible_user_id }}/InputMonoNarrow-Regular.ttf' }
    - { src: 'files/etc/fonts/conf.d/30-font-aliases.conf', dest: '/etc/fonts/conf.d/30-font-aliases.conf' }
    - { src: 'files/etc/fonts/conf.d/75-joypixels.conf', dest: '/etc/fonts/conf.d/75-joypixels.conf' }
    - { src: 'files/etc/systemd/journald.conf.d/override.conf', dest: '/etc/systemd/journald.conf.d/override.conf' }
    - { src: 'files/etc/systemd/logind.conf.d/override.conf', dest: '/etc/systemd/logind.conf.d/override.conf' }

- name: enable system services
  systemd:
    name: "{{ item }}"
    enabled: yes
  loop:
    - "NetworkManager.service"
    - "bluetooth.service"
    - "docker.socket"
    - "tlp.service"
    - "reflector.timer"
    - "pcscd.service"

- name: ensure group "docker" exists
  group:
    name: docker
    state: present

- name: add {{ ansible_user_id }} to "docker" group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

- name: check if office VPN is present
  stat:
    path: "/etc/NetworkManager/system-connections/office.nmconnection"
  register: office_vpn_status

- name: import the Office VPN settings if it dont exists yet
  shell: "nmcli connection import type openvpn file /run/media/aljaz/wrk-stick/work/vpn/office/office.ovpn"
  when: not office_vpn_status.stat.exists

- name: Recursively change ownership of the Intellij directory
  file:
    path: /opt/intellij-idea-ultimate-edition
    state: directory
    recurse: yes
    owner: "{{ ansible_user_id }}"
