---
- name: Enable user services
  systemd:
    name: "{{ item }}"
    enabled: yes
    scope: user
  loop:
    - "udiskie.service"
    - "waybar.service"
    - "waybar-updates.timer"
    - "sway-inactive-window-transparency.service"
    - "wlsunset.service"
    - "yubikey-touch-detector.socket"
    - "polkit-gnome.service"
  tags:
    - systemd

- name: Recursively change ownership of the Intellij directory
  file:
    path: /opt/intellij-idea-ultimate-edition
    state: directory
    recurse: yes
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  become: true
  tags:
    - idea

- name: Install personal key and set trust level 5
  gpg_key:
    fpr: 7E2A21F965AD08B06B6924881C64943243A3151D
    keyserver: keys.openpgp.org
    trust: '5'
  tags:
    - gpg

- name: Configuring YubiKey for passwordless sudo (touch it now)
  command: "mkdir {{ ansible_user_dir }}/.config/Yubico && pamu2fcfg -umaximbaz > {{ ansible_user_dir }}/.config/Yubico/u2f_keys"
  args:
    creates: "{{ ansible_user_dir }}/.config/Yubico"
