---
- name: Enable user services
  systemd:
    name: "{{ item }}"
    enabled: yes
    scope: user
  loop:
    - "udiskie.service"
    - "waybar.service"
    - "waybar-updates.timer"
    - "sway-inactive-window-transparency.service"
    - "wlsunset.service"
  tags:
    - systemd
