---
block:
    - name: Clone yay repository
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: "{{ ansible_env.HOME }}/yay"
        version: "master"

    - name: Install yay
      shell: >-
        echo "y" | makepkg -si
      args:
        chdir: "{{ ansible_env.HOME }}/yay"

    - name: Remove yay repository
      file:
        state: absent
        path: "{{ ansible_env.HOME }}/yay"

  when: "'yay' not in ansible_facts.packages"
    tags:
      - yay