---
- name: Enable user services
  systemd:
    name: "{{ item }}"
    enabled: yes
    scope: user
  loop:
    - "udiskie.service"
    - "waybar.service"
    - "waybar-updates.timer"
    - "sway-inactive-window-transparency.service"
    - "wlsunset.service"
    - "yubikey-touch-detector.socket"
    - "polkit-gnome.service"
  tags:
    - systemd

- name: Recursively change ownership of the Intellij directory
  file:
    path: /opt/intellij-idea-ultimate-edition
    state: directory
    recurse: yes
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  become: true

- name: Create the Yubico directory if it does not exist
  file:
    path: "{{ ansible_user_dir }}/.config/Yubico"
    state: directory
    mode: '0755'

- name: Configuring YubiKey for passwordless sudo (touch it now)
  command: "pamu2fcfg -umaximbaz > {{ ansible_user_dir }}/.config/Yubico/u2f_keys"
  args:
    creates: "{{ ansible_user_dir }}/.config/Yubico/u2f_keys"
