autoclip: false
autoimport: true
cliptimeout: 45
exportkeys: true
nopager: false
notifications: false
parsing: true
path: /home/aljaz/.local/share/gopass/stores/root
safecontent: false
mounts:
    lando: /home/aljaz/.local/share/gopass/stores/lando
    lando-devel: /home/aljaz/.local/share/gopass/stores/lando-devel
