---
- name: Playbook to manage mordax777 dotfiles (https://github.com/mordax777/dotfiles)
  hosts: localhost
  connection: local
  tasks:
    - name: Gather package facts
      package_facts:
        manager: auto

    - name: Clone ansible-aur repository into user custom-module directory
      git:
        repo: https://github.com/kewlfft/ansible-aur.git
        dest: "{{ ansible_env.HOME }}/.ansible/plugins/modules/aur"
        version: "master"

    - include: tasks/packages.yml
      tags:
        - packages

    - include: tasks/system.yml
      become: true
      tags:
        - system

    - include: tasks/harden.yml
      become: true
      tags:
        - harden

    - include: tasks/user.yml
      tags:
        - user