---
- name: Playbook to manage mordax777 dotfiles (https://github.com/mordax777/dotfiles)
  hosts: localhost
  connection: local
  tasks:
    - import_tasks: tasks/packages.yml
      tags:
        - packages

    - import_tasks: tasks/system.yml
      become: true
      tags:
        - system

    - import_tasks: tasks/harden.yml
      become: true
      tags:
        - harden

    - import_tasks: tasks/user.yml
      tags:
        - user
